default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: aws_s3_sdk_sample_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

test:
  <<: *development
  database: active_store_test

production:
  <<: *default
  host: <%= Rails.application.credentials.dig :database, :host %>
  username: <%= Rails.application.credentials.dig :database, :username %>
  database: <%= Rails.application.credentials.dig :database, :name %>
  password: <%= Rails.application.credentials.dig :database, :password %>
